tasks:
  - name: Python Environment
    before: pyenv install 3.9.6 && pyenv global 3.9.6
    env:
      PIP_USER: false
    init: pip install poetry
    command: poetry install && poetry run pre-commit install

vscode:
  extensions:
    - ms-python.vscode-pylance
    - ms-python.python
