name: Create Sentry release

on: workflow_call

jobs:
  create_sentry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.3.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: python-discord
          SENTRY_PROJECT: sir-lancebot
        with:
          tagName: ${{ github.sha }}
          environment: production
          releaseNamePrefix: sir-lancebot@
